version: "3.9"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./.dev_database/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_dev
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
